### ISSUE TITLE
Publish the memory book on 19th July

### ISSUE THREAD

**Issue by joereddington** [joereddington/Projects-Public#35]
To publish the book and have it on amazon. 

# Resources 
* [the manual for Tikx, which I'm using for diagrams](https://www.bu.edu/math/files/2013/08/tikzpgfmanual.pdf) if we are going to use PGF (and it appears to be the standard

# Timings
19/7/2021 Publish
15/7/2021 Have everything set up on Kingle Self Publishing
7/7/2021 Get all version back from proofreaders. 
1/7/2021 Send updated version to proofreaders. 

# Cover notes

# TODO 
- [x] Get cover designed
   - [x] Put sketch on social media 
   - [x] Put sketch on reddit 
   - [x] Get back to Michelle about changes
  -  [x] Get some feedback from Simon about the cover. 
- [x] Do test publish on Amazon looking for issues. 
   - [x] Fix the width of tables 
   - [x] Fix the overflow in 'classes you've already seen' 
- [x] Draw all the diagrams 
   - [x] Put tikx files in their own folder
   - [x] Read the manual at https://www.bu.edu/math/files/2013/08/tikzpgfmanual.pdf
   - [x] Make list of the diargams to make. 
- [x] Beta Readers get the first four chapters 
   - [x] Put changes in for first four chapters 
- [x] Finish putting in Kat's changes 
- [x] Index index index
- [x] Complete writing the Conclusion chapter 
- [x] Send whole thing to beta readers via the facebook groups. 
- [x] Make marketing a seperate issue

**Comment by joereddington** [comment]
Today I drafted the cover email and spent an hour working out diagrams. (Reading the manual and doing some tests. I believe I've got the structure sorted out) 

Seperately 
## 14/04/20 08:21 to 09:23, Working on the tree diagam 
* It's done (and like all latex looks really good when it's good and terrible otherwise) 
* I still need to work out special arrows
* I need to insert the other diagrams yet, but they can appear on a 'as needed' basis

Reading the manual first was a good idea - it took a long time even when I did understand what was happening.

**Comment by joereddington** [comment]
## 15/04/20 07:05 to 09:10, Memory book +PersonalProjects
I complete rewrote the introduction chapter today. It's shorter, but vastly better. I'm now I bit worried that the book itself is going to be too short. Worth dealing with.
The next actions for the book are:

* More diagram
* Finnish going through the printout
* Order next printout
* Read the other books
* DO the rest of the todos
* Insert the images (because now you have a local copy)

**Comment by joereddington** [comment]
Okay, so following the early birth of my child, we're going to change some aspects of this. 

Going to rewrite the targets.

**Comment by joereddington** [comment]
## 09/05/20 19:35 to 21:20, Working on https://github.com/joereddington/Projects-Public/issues/35 
* Have done reddit post at https://www.reddit.com/r/Mnemonics/comments/ggl4n8/feedback_wanted_for_my_book_cover_concept/
* Reviewed IH edits
* Pushed the vimrc to github
* Spoke to Kat 
* Read the notes from Beta readers 
* Installed a latex plugin. 
* Did the Lyle's corrections for the first chapter. 

My next action is to do the first chapter corrections for the other two readers and then do my own changes. 
I've not worked out the latex plugin yet. It's nice having the quickfix list working, but I'm not getting that much out of it yet.

**Comment by joereddington** [comment]
## 13/05/20 21:00 to 21:44, Working on https://github.com/joereddington/Projects-Public/issues/35 
So let's prep for it. I've opened the file, changed the vim background so it's obvious and am working on it.  I've also done a bunch of comments

## 14/05/20 07:07 to 08:05, Working on #35
* Big job was rearranging all of the footnoes
* Have put in the corrections for A and I for the first chapter (and immogens for the whole book)

Next action is putting the corrections into the second chapter (or even the whole rest of it.

**Comment by joereddington** [comment]
Today I've been working on diagrams.
## 20/07/20 05:46 to 05:57, 

* I'm thinking that diagrams should be in their own seperate folder and \input'd
  * Have done one as a test 
  * Finally got to use my memorised filename shortcut 
  * All are done by 5:56 
  * Now to create some new ones. 


## 20/07/20 05:56 to 06:13, Diagram for skip list 
* I created a wrapper, 
* Started working on the linked list president document 

## 20/07/20 09:38 to 10:35, Completed a diagram 
* Learned about the \resizebox command, which is excellent. 
* Placed some invisible boxes
* Added some lines and understood a bit more about the process



## 20/07/20 13:59 to 14:15, unbalanced tree diagram 
* We're now up to 145 pages and I learned about set nrformats+=alpha

What's next? 

## 20/07/20 14:15 to 14:45, 
I'm working on the decision tree, I've got a list of 16 things and I've worked out how to add labels to diagrams 


## 20/07/20 14:58 to 15:16,
I'm getting annoyed that moving { causes a parse error and the next action is to sort a MCVE.  I've asked a question here: https://tex.stackexchange.com/q/554302/10771 

In general, the tree is getting build, which is cool.

**Comment by joereddington** [comment]
Okay, where am I? 

* See if you have really completed the chapter about Classes 
* Go over the chapter about trees. 
* Diagrams. 

Right now - see if you can ssh into the streaming account

**Comment by joereddington** [comment]
Use https://apple.stackexchange.com/a/126306/16077 to use a different users account.

**Comment by joereddington** [comment]
Did a solid sprint on this, inclduing completing one of the diagrams today.  

There's a lot left to do on it, but there are also some really interesting sections.

**Comment by joereddington** [comment]
I think I'm waiting for Kat to finnish aren't I? Or I'm 

* Fixing the cover 
* Rewriting the outside
* Putting in the issues I've already found 
* doing more diagram work. 

That's all important. I'd like Kat to complete though while I do other THINGs

**Comment by joereddington** [comment]
![Screenshot 2020-11-19 at 10 17 01](https://user-images.githubusercontent.com/4369547/99947791-6b04dd00-2d70-11eb-868f-7ffb203b4c40.png)

**Comment by joereddington** [comment]
There's actually been quite a lot of work on this. But the cover does need to be changed again, which is a shame. 

Currently I'm about halfway through the second chapter with simplewriter, and that's annoying because I simply need to get back in the habit.

**Comment by joereddington** [comment]
Did a solid sprint on this today. 

Two more pages, quite a lot of the tree chapter is looking nicer and brighter and holds together better - I fixed the annoying family tree issue by putting it at he end, I wrote a couple of summaries and some signposting and fixed diagrams. I also included a diagram that was missing and I'm trialing an new way of doing decision trees.  

next actions are to complete the decision tree diagrams and finish rewriting the decision tree text. I also need to move the diagram of the unbalanced tree up a little bit.   

I should bite the bullet and accept that I need to edit, like, ten pages out of this chapter.  

So, the todo: 

* Redo the decision tree diagrams
* Rewrite the decision tree text
* Write the new world cup section (probably the easist) this would include a couple of diagrams and add a couple of pages. 
 * Start again at the begining of the chapter with simplewriter and with TTS. 
 * Next two chapters
 * Get a printout done

**Comment by joereddington** [comment]
I'm working through a draft that I had printed as a way of getting myself started again.

**Comment by joereddington** [comment]
I did a solid week's push - the details are here: https://joereddington.github.io/2021/06/17/Book-is-ready-for-final-readers!.html

It's now with 11 reviewers (10 magic people and one International Development Person.

**Comment by joereddington** [comment]
Left to do: 

* Cover again
* Marketing issue. j
* Find some teachers/education groups on facebook for beta readers.

**Comment by joereddington** [comment]
Okay, it's gone to my VIP. 

Next actions 
- [ ] Send the reference emails 
- [ ] Ask for final proofreaders
- [ ] Get Cover update 
- [ ] Set date to badger the VIP 
- [ ] Press the damn button 
- [ ] Set up marketing issue.

**Comment by joereddington** [comment]
## 14/09/21 15:52 to 16:35, Working https://github.com/joereddington/Projects-Public/issues/35 
* emailed cover designer
* Fixed some bits

**Comment by joereddington** [comment]
Sucessfully done! https://www.amazon.co.uk/Joe-Reddington/dp/B09GJFZ6JM
